name: "Build"

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build lifecycle

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17
          check-latest: true

      - name: Initialize gradle caching
        uses: burrunan/gradle-cache-action@v1
        with:
          job-id: jdk17
          concurrent: true

      - name: Run build lifecycle
        run: ./gradlew build checkLicenses test jar --stacktrace
