name: "Build"

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '8', '11', '17' ]
    name: Java ${{ matrix.java }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          check-latest: true
          cache: 'gradle'

      - name: Run build lifecycle
        run: ./gradlew build checkLicenses test jar --stacktrace

      - name: Release ZIP
        run: |
          mkdir -p temp/;

          cp -r .template/* temp/;
          cp LICENSE temp/license.txt;

          mkdir temp/dev;
          mkdir temp/dev/examples;
          cp -r cloudnet-examples/src/main/java/de/dytanic/cloudnet/examples/* temp/dev/examples;

          mkdir temp/plugins;
          cp cloudnet-plugins/**/build/libs/*.jar temp/plugins/;
          cp cloudnet-launcher/build/libs/launcher.jar temp/launcher.jar;

      - uses: actions/upload-artifact@v2
        with:
          name: CloudNet-v3
          path: temp/
